### ISSUE TITLE
 Exception in queued task: Error: ENOENT, no such file or directory

### ISSUE THREAD

**Issue by chip** [blazer82/meteor-casperjs#2]
Hi, I'm trying to use this with `velocity:html-reporter` and am receiving the following error after clicking on the button in html-reporter that adds a Casperjs test:

```
meteor
[[[[[ ~/code/meteor.chipcastle.com ]]]]]      

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
I20141210-12:15:47.406(-6)? [casperjs] Run tests for file /Users/chip/code/meteor.chipcastle.com/tests/casperjs/sampleTest.coffee...
I20141210-12:15:48.219(-6)? Exception in queued task: Error: ENOENT, no such file or directory '/Users/chip/code/meteor.chipcastle.com/tests/.reports/casperjs/sampleTest.coffee.xml'
I20141210-12:15:48.220(-6)?     at Object.fs.openSync (fs.js:432:18)
I20141210-12:15:48.221(-6)?     at Object.fs.readFileSync (fs.js:289:15)
I20141210-12:15:48.221(-6)?     at parseReport (packages/nblazer:casperjs/nblazer:casperjs.coffee:74:17)
I20141210-12:15:48.221(-6)?     at Object.runTestFile (packages/nblazer:casperjs/nblazer:casperjs.coffee:61:1)
I20141210-12:15:48.221(-6)?     at observeChangesCallbacks.added (packages/minimongo/observe.js:153)
I20141210-12:15:48.221(-6)?     at self.applyChange.added (packages/minimongo/observe.js:53)
I20141210-12:15:48.221(-6)?     at packages/mongo/observe_multiplex.js:163
I20141210-12:15:48.221(-6)?     at Array.forEach (native)
I20141210-12:15:48.221(-6)?     at Function._.each._.forEach (packages/underscore/underscore.js:105)
I20141210-12:15:48.221(-6)?     at Object.task (packages/mongo/observe_multiplex.js:157)
```

My project has the following packages installed:

```
accounts-base                 1.1.2  A user account system
accounts-password             1.0.4  Password support for accounts
accounts-ui                   1.1.3  Simple templates to add login widgets to an app
alanning:roles                1.2.13  Role-based authorization
anti:fake                     0.4.1  Random text and data generator
cmather:handlebars-server     0.2.0* Allows handlebars templates to be defined on the server in .handlebars files
coffeescript                  1.0.4  Javascript dialect with fewer braces and semicolons
cunneen:mailgun               0.9.1  Easily send emails using Mailgun as your email provider.
dburles:collection-helpers    1.0.1  Transform your collections with helpers that you define
dburles:factory               0.3.7  Factories for Meteor
fuatsengul:iron-router-auth   1.0.7  Iron:Router Auth for 1.0
iron:router                   1.0.3  Routing specifically designed for Meteor
joshowens:accounts-entry      1.0.3  Make signin and signout their own pages with routes.
joshowens:simple-form         0.2.2  A meteorite package that makes building dynamic two way forms easy
less                          1.0.11  The dynamic stylesheet language
manuelschoebel:ms-seo         0.4.1  Easily config SEO for your routes
matb33:collection-hooks       0.7.6  Extends Mongo.Collection with before/after hooks for insert/update/remove/find/findOne
meteor-platform               1.2.0  Include a standard set of Meteor packages in your app
meteorhacks:zones             1.4.0  Zone.Js integration for meteor
mrt:moment                    2.8.1  Moment.js, a JavaScript date library for dates, packaged for Meteor. See http://momentjs.com.
mrt:underscore-string-latest  2.3.3  underscore.string repackaged for Meteor
nblazer:casperjs              0.1.6  CasperJS end to end test integration with velocity.
reywood:publish-composite     1.3.5  Publish a set of related documents from multiple collections with a reactive join
velocity:html-reporter        0.3.1  Reactive Velocity test reports in your app.
zimme:iron-router-active      1.0.1  Active route/path template helpers for iron:router
```

Any clues on how to fix or troubleshoot would be appreciated.  Thanks. :smile:

**Comment by drenfr01** [comment]
Hi All,

I just hit that this bug as well. Is there anything I can do to help resolve it? Like Chip, I'm new to the community but definitely willing to dive in.

Cheers,
Duncan

**Comment by blazer82** [comment]
@drenfr01 @chip I appreciate your offer to help, thank you guys! I've got zero resources to work on this project right now. So, by all means, you are very welcome to help :)
First thing for you to do would be to fork this repository (you know how to fork on github?). As soon as you've got your forked repo on your local dev environment, you just need to link to the repo from inside your meteor project, so that meteor uses your local source code of this package instead of the official package.

So, let's say you've got your forked version of this repository at the following path:
`/path/to/your/workspace/nblazer:casperjs`

And your own app might be here:
`/path/to/your/workspace/yourmeteorapp`

You then need to create a `packages` directory inside your app folder:
`/path/to/your/workspace/yourmeteorapp/packages`

Inside of this directory you need to link to the casperjs package. The link will look something like this:
`nblazer:casperjs -> ../../nblazer:casperjs`

The next time you start your meteor app, it should use the linked package which means you can edit the code of the package and test it with your own app.
(Make sure the package remains listed in the `.meteor/packages` file of your app!)

Once you've done some changes to the package you'd like to publish, create a pull request on github and I'll merge your code.

Hope this helps.

If there are any further questions, don't hesitate to ask! I'll try to help!
And thanks again for your help!! I really appreciate it since I'm unable to fix things myself.

**Comment by keyscores** [comment]
@blazer82 
Having same issue here. I haven't got this package to work with the default configs and sample tests. I've tried a few things in this (long) thread to no avail.
I know you are busy, but can I ask you to update the documentation and samples for this?

**Comment by pmp0x** [comment]
Hey,
for me the issue laid within casperjs. Have you tried run it manually? e.g. 
'casperjs test file.js'

For me that gave me an error. So as it seems the homebrew version is shipping phantomjs 2.0 but casperjs (devel) can just handel phantomjs 1.X

See [ticket](https://github.com/n1k0/casperjs/pull/1154) 
for me replacing bootstrap.js inside 
'/usr/local/Cellar/casperjs/1.1-beta3/libexec/bin' with [this one](https://gist.githubusercontent.com/rdpanek/867fc40e68c3160739e1/raw/b785bdf1322b0265a30283fb2f4df460b823f1b2/bootstrap.js) helped ;)

**Comment by blazer82** [comment]
@chip, @samhatoum, @drenfr01, @keyscores, @pmp0x 
Please read my comment on [8#issuecomment-90605956](https://github.com/blazer82/meteor-casperjs/issues/8#issuecomment-90605956), thank you!
