### ISSUE TITLE
Exception in queued task: TypeError: Cannot read property 'testsuite' of undefined

### ISSUE THREAD

**Issue by jhartma** [blazer82/meteor-casperjs#3]
Hi there, I started a vanilla project, added casperjs + example tests and ran into this error:
```
Exception in queued task: TypeError: Cannot read property 'testsuite' of undefined
at packages/nblazer:casperjs/nblazer:casperjs.coffee:75:3
at Parser.<anonymous> (/home/knut/.meteor/packages/nblazer_casperjs/.0.1.6.ag867e++os+web.browser+web.cordova/npm/node_modules/xml2js/lib/xml2js.js:384:20)
at Parser.emit (events.js:95:17)
at Object.onclosetag (/home/knut/.meteor/packages/nblazer_casperjs/.0.1.6.ag867e++os+web.browser+web.cordova/npm/node_modules/xml2js/lib/xml2js.js:348:26)
at emit (/home/knut/.meteor/packages/nblazer_casperjs/.0.1.6.ag867e++os+web.browser+web.cordova/npm/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
at emitNode (/home/knut/.meteor/packages/nblazer_casperjs/.0.1.6.ag867e++os+web.browser+web.cordova/npm/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)
at closeTag (/home/knut/.meteor/packages/nblazer_casperjs/.0.1.6.ag867e++os+web.browser+web.cordova/npm/node_modules/xml2js/node_modules/sax/lib/sax.js:861:5)
at Object.write (/home/knut/.meteor/packages/nblazer_casperjs/.0.1.6.ag867e++os+web.browser+web.cordova/npm/node_modules/xml2js/node_modules/sax/lib/sax.js:1294:29)
at Parser.exports.Parser.Parser.parseString (/home/knut/.meteor/packages/nblazer_casperjs/.0.1.6.ag867e++os+web.browser+web.cordova/npm/node_modules/xml2js/lib/xml2js.js:403:31)
at Parser.parseString (/home/knut/.meteor/packages/nblazer_casperjs/.0.1.6.ag867e++os+web.browser+web.cordova/npm/node_modules/xml2js/lib/xml2js.js:6:61)
Exception in queued task: Error: Unknown id for changed: /home/knut/Dokumente/Programming/meteor/playground/casperjs/tests/casperjs/sampleTest.coffee
at self.applyChange.changed (packages/minimongo/observe.js:65:1)
at packages/mongo/observe_multiplex.js:163:1
at Array.forEach (native)
at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
at Object.task (packages/mongo/observe_multiplex.js:157:1)
at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:145:1)
at packages/meteor/fiber_helpers.js:123:1
```
any ideas? casperjs is fully installed

**Comment by blazer82** [comment]
I'm closing this then, okay?
