### ISSUE TITLE
casperjs and jasmine don't work well together

### ISSUE THREAD

**Issue by miguelalarcos** [blazer82/meteor-casperjs#4]
I've just created a new app and added ``nblazer:casperjs``. I've created a file in tests/casperjs/ directory with the code of the example and it's all ok.

But when I add ``sanjo:jasmine`` I get the error "ReferenceError: casper is not defined".

Maybe it's not a problem of ``nblazer:casperjs`` but of ``sanjo:jasmine``, I don't know. Have you got any clue? Thanks in advance.

**Comment by miguelalarcos** [comment]
I've read that thread and got the same error: ReferenceError: Can't find variable: Meteor.

The test is under ``tests/casperjs/server`` and starts like this:

```coffee
return unless Meteor.isServer and process.env.IS_MIRROR
```

Please tell me if I can do something to help. Thanks.

**Comment by samhatoum** [comment]
very odd! Could you create a reproducible repo and I can look

**Comment by miguelalarcos** [comment]
https://github.com/miguelalarcos/appCasperJasmine.git

By the way, casperjs tests should be always in server folder?

**Comment by samhatoum** [comment]
I won't be able to look at this for a couple of days as I'm off to a beach-house! I'll do my best to look on Sunday

**Comment by miguelalarcos** [comment]
have a nice weekend :)

**Comment by samhatoum** [comment]
Hi. I'm not able to start the repo. When I check it out, I get:

```
Exception in queued task: Error: ENOENT, no such file or directory '/Users/sam/WebstormProjects/meteor-testing/appCasperJasmine/tests/.reports/casperjs/test_casperjs.coffee.xml'
   at Object.fs.openSync (fs.js:438:18)
   at Object.fs.readFileSync (fs.js:289:15)
   at parseReport (/Users/sam/WebstormProjects/meteor-testing/appCasperJasmine/.meteor/local/build/programs/server/packages/nblazer_casperjs.js:123:25)
   at Object.runTestFile (/Users/sam/WebstormProjects/meteor-testing/appCasperJasmine/.meteor/local/build/programs/server/packages/nblazer_casperjs.js:104:10)
   at [object Object].observeChangesCallbacks.added (/Users/sam/WebstormProjects/meteor-testing/appCasperJasmine/.meteor/local/build/programs/server/packages/minimongo.js:3879:28)
   at self.applyChange.added (/Users/sam/WebstormProjects/meteor-testing/appCasperJasmine/.meteor/local/build/programs/server/packages/minimongo.js:3779:44)
   at /Users/sam/WebstormProjects/meteor-testing/appCasperJasmine/.meteor/local/build/programs/server/packages/mongo.js:1703:30
   at Array.forEach (native)
   at Function._.each._.forEach (/Users/sam/WebstormProjects/meteor-testing/appCasperJasmine/.meteor/local/build/programs/server/packages/underscore.js:139:11)
   at Object.task (/Users/sam/WebstormProjects/meteor-testing/appCasperJasmine/.meteor/local/build/programs/server/packages/mongo.js:1697:9)
   at [object Object]._.extend._run (/Users/sam/WebstormProjects/meteor-testing/appCasperJasmine/.meteor/local/build/programs/server/packages/meteor.js:785:18)
   at /Users/sam/WebstormProjects/meteor-testing/appCasperJasmine/.meteor/local/build/programs/server/packages/meteor.js:763:14

```

@blazer82 is this some other error?

**Comment by miguelalarcos** [comment]
I'm sorry, I cannot reproduce that error you say. I can clone the app without any problem, and that file ```test_casperjs.coffee.xml``` is in the repository. I would like to help. ¿You can see that file in your cloned repository?

**Comment by Sanjo** [comment]
I just found this issue.

To fix this problem you need to move all your casperjs tests into `tests/casperjs/features/`.
And you need to remove the first line `return unless Meteor.isServer and process.env.IS_MIRROR`. Meteor is not available when the CasperJS test run.

@samhatoum 
The problem is that the casperjs tests gets included in the tests-proxy package (https://github.com/meteor-velocity/node-soft-mirror/blob/develop/testProxyPackage/sync.js#L181-L184)

**Comment by miguelalarcos** [comment]
Thank you.
